language: rust
sudo: false
node_js: "12.4.0"

cache:
  - cargo
  - directories:
    - "node_modules"

branches:
  only:
    - master

before_install:
  - cargo install wrangler || echo "wrangler already installed"

install:
  - npm install

script:
  - wrangler config "${CF_EMAIL}" "${CF_API_KEY}"
  - cp wrangler.toml.sample wrangler.toml
  - sed -i "s/CF_ACCOUNT_ID/${CF_ACCOUNT_ID}/g" wrangler.toml
  - wrangler whoami
  - wrangler publish

after_success:
  - cd worker
  - git init
  - git config user.name "AutoBuilder@Traivs"
  - git config user.email "auto_builder_by_traivs@rhilip.info"
  - git add *
  - git commit --message "Travis build"
  - git push --force --quiet "https://${GITHUB_USERNAME}:${GITHUB_API_KEY}@${GITHUB_REF}" master:build
